name: Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run doc
      - run: |
          git config --global user.name 'wafful-node-package'
          git config --global user.email 'wafful-node-package@users.noreply.github.com'
          git diff --quiet || git commit -am "chore: automated doc generation"
          git push
